[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pescador"
authors = [{name = "mat-fox", email = "materialeszorro@gmailcom"}]
dynamic = ["version", "description"]
